version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: users_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users_db
    ports:
      - '27017:27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
