version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: users_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users_db
    ports:
      - '27027:27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379